// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAgQHPayT0owJzeKr3YaklR94kztD2X7I',
    appId: '1:595172733798:web:c924a3b3347b0b246d4ea7',
    messagingSenderId: '595172733798',
    projectId: 'opsw-manager',
    authDomain: 'opsw-manager.firebaseapp.com',
    storageBucket: 'opsw-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXEIqfyJR4aTYQXHP65xNYWmQI1wms5r4',
    appId: '1:595172733798:android:5102d86166f451bf6d4ea7',
    messagingSenderId: '595172733798',
    projectId: 'opsw-manager',
    storageBucket: 'opsw-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA00LtwDm1uqOvt4NHcU4mcpf__MIzpK5Q',
    appId: '1:595172733798:ios:1368e5bd196c50696d4ea7',
    messagingSenderId: '595172733798',
    projectId: 'opsw-manager',
    storageBucket: 'opsw-manager.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA00LtwDm1uqOvt4NHcU4mcpf__MIzpK5Q',
    appId: '1:595172733798:ios:1368e5bd196c50696d4ea7',
    messagingSenderId: '595172733798',
    projectId: 'opsw-manager',
    storageBucket: 'opsw-manager.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAgQHPayT0owJzeKr3YaklR94kztD2X7I',
    appId: '1:595172733798:web:e0be9e0b4d81c3cc6d4ea7',
    messagingSenderId: '595172733798',
    projectId: 'opsw-manager',
    authDomain: 'opsw-manager.firebaseapp.com',
    storageBucket: 'opsw-manager.firebasestorage.app',
  );

}